name: Zip Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Files
        run: |
          zip -r extension.zip extension/
        working-directory: ${{ github.workspace }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Log Version
        run: echo ${{ steps.tag_version.outputs.new_tag }}
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "extension.zip"
          tag: "latest"
          token: ${{ secrets.GITHUB_TOKEN }}
