name: Zip extension

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Files
        run: |
          zip -r extension.zip extension/
        working-directory: ${{ github.workspace }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          files: extension.zip
          tag_name: latest 
          release_name: latest
          draft: false
          prerelease: false

      - name: Publish Release
        run: echo "Released ${{ steps.create_release.outputs.upload_url }}"
