name: Zip extension

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Files
        run: |
          zip -r extension.zip extension/
        working-directory: ${{ github.workspace }}

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "extension.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
